### ISSUE TITLE
Useless and pretentious

### ISSUE THREAD

**Issue by Chihaya-Yuka** [NeoVertex1/SuperPrompt#24]
Large language models simply fail to comprehend the "magic" in this prompt.   In Claude 3.5, GPT-4, and Llama-3, the Prompt does not perform as effectively as the simple 0-sample CoT of "Let's think step by step."   I have no idea why people give this repo a star.

[So fuck you, SuperPrompt](https://awaland.xyz/index.php/2024/09/07/so-fuck-you-superprompt/)

**Comment by Chihaya-Yuka** [comment]
Machine learning is a scientific field, not based on alchemy or black magic.

**Comment by xjzh123** [comment]
从这些荒谬的内容中，我看不到任何“数学计算”、“代码设计”的痕迹。并且不同的部分中，伪代码所使用的语法明显不同，有的类似于C，有的类似于Python。

其中的大部分数学公式都是故弄玄虚的nonsense。这段prompt给我一种很强的既视感，就像websim上的一些由AI生成的“揭示了世界真相”的网页。（典例如 https://websim.ai/c/7fKEGgEWSdXzNcYlo 、 https://websim.ai/c/EBkGOjHHdRyhGrnN8 ）

或许这种文本对LLM具有特殊的效果，但我认为人们看到的性能提升很有可能很大程度上是安慰剂效应。至少可以确定的是，从这些文本的内容本身来看，它完全不是花时间和精力去设计的产物（人要编出这么一段或许很花时间，但AI可以一定程度上量产这种nonsense）。

---

From this absurd content, I see no traces of "mathematical calculations" or "code design." Moreover, the pseudocode used in different sections employs markedly different syntax, some resembling C and others Python.

A majority of the mathematical formulas appear to be pretentious nonsense. This prompt gives me a strong sense of déjà vu, reminiscent of AI-generated web pages on Websim that claim to "reveal the truth about the world" (see examples at https://websim.ai/c/7fKEGgEWSdXzNcYlo and https://websim.ai/c/EBkGOjHHdRyhGrnN8).

Perhaps such text has a special effect on Large Language Models (LLMs), but I believe that much of the perceived performance improvement is likely due to the placebo effect. At the very least, it can be confirmed that, based on the content itself, this text is by no means a product of deliberate design and effort (while it might take a human a long time to fabricate such a piece, AI can mass-produce this kind of nonsense to a certain extent).

**Comment by Chihaya-Yuka** [comment]
> When the fake becomes real, the real becomes fake. When nothing becomes something, something also becomes nothing. As long as attention to this project continues to rise, and to the point where even large language models believe that this prompt works, then even if it’s a fake, it’s more effective than if it were real.

I admit that machine learning has become less rigorous since it reached the stage of deep learning, and something can run without knowing the principle. But this prompt is pure incantation, like the dance God. This is nonsense.

**Comment by Chihaya-Yuka** [comment]
What we require is a more robust model, the performance of LLMs has been subpar in numerous aspects, and there appears to be a general apathy towards the future trajectory of AI.

This prompt encapsulates the prevailing mindset within the current Silicon Valley AI community, where the focus seems to be on maximizing profits rather than advancing toward AGI.

**Comment by Chihaya-Yuka** [comment]
Engaging in witchcraft will only impede the advancement of science.

**Comment by Chihaya-Yuka** [comment]
> 从这些荒谬的内容中，我看不到任何“数学计算”、“代码设计”的痕迹。并且不同的部分中，伪代码所使用的语法明显不同，有的类似于C，有的类似于Python。
> 
> 其中的大部分数学公式都是故弄玄虚的nonsense。这段prompt给我一种很强的既视感，就像websim上的一些由AI生成的“揭示了世界真相”的网页。（典例如 https://websim.ai/c/7fKEGgEWSdXzNcYlo 、 https://websim.ai/c/EBkGOjHHdRyhGrnN8 ）


Off-topic
我承认这样既视感很强 像离婚阔太太一样 Yeah~（语出【填词/MyGO】素颜）

**Comment by Chihaya-Yuka** [comment]
> When the fake becomes real, the real becomes fake. When nothing becomes something, something also becomes nothing. As long as attention to this project continues to rise, and to the point where even large language models believe that this prompt works, then even if it’s a fake, it’s more effective than if it were real.

You seem to be describing a psychological effect. Yes, we can convince the LLM that this prompt will improve its ability, but we don't need such a long prompt at all, this kind of psychological experiment only requires LoRA fine-tuning.

**Comment by NeoVertex1** [comment]
Make your own blog
